CREATE DATABASE movies;
CREATE DATABASE artists;
CREATE DATABASE notification;
CREATE DATABASE roles;
CREATE USER movie_user WITH ENCRYPTED PASSWORD 'nevermind';

GRANT ALL PRIVILEGES ON DATABASE movies TO movie_user;
GRANT ALL PRIVILEGES ON DATABASE artists TO movie_user;
GRANT ALL PRIVILEGES ON DATABASE notification TO movie_user;
GRANT ALL PRIVILEGES ON DATABASE roles TO movie_user;